### ISSUE TITLE
List is empty after locking the screen

### ISSUE THREAD

**Issue by ckotte** [RaphaelRochet/arch-update#154]
I have to click Check now to see the updates again.

**Before screen lock**
![image](https://user-images.githubusercontent.com/8488565/95976008-3750a200-0e17-11eb-9a4f-ac47e6bbc4e7.png)

**After log on**
![image](https://user-images.githubusercontent.com/8488565/95975878-08d2c700-0e17-11eb-9f44-9a3c44d1da2b.png)

This happens on Xorg and Wayland. I tested it with my laptop and a VM.

**Comment by RaphaelRochet** [comment]
Hi @ckotte 
Thanks for reporting this one. I must admit I've seen it a few times but didn't bother to fix, thinking it was only me.
Will fix it asap.

**Comment by ckotte** [comment]
It's not a big deal, but just a bit annoying if I work with multiple computers and the screen gets locked. 

> Will fix it asap.

Nice. Thanks.

**Comment by RaphaelRochet** [comment]
Should by fixed by ad556a34d621ffbda2e05c4fccc758a4c2f131a5 (in master)
Can you give it a try ?

**Comment by ckotte** [comment]
It's fixed! Thanks.

**Comment by moshiur-raj** [comment]
I am still facing this issue.
![image](https://user-images.githubusercontent.com/36466700/100534775-bb7ead80-323c-11eb-9cc3-50399d56c9a0.png)
![image](https://user-images.githubusercontent.com/36466700/100534787-ca656000-323c-11eb-94e2-0a0b86ebde93.png)

**Comment by RaphaelRochet** [comment]
Did you just updated to v38 ?
Does it reproduce everytime you lock you screen ?

**Comment by moshiur-raj** [comment]
Yes, I installed the extension yesterday. Every time I lock my screen it happens.

**Comment by RaphaelRochet** [comment]
I can't reproduce it unfortunately.
When you run "Check Now", the list is correctly populated ?
Also, the fix I just pushed on master may help on this. Can you try latest build from master ?

**Comment by moshiur-raj** [comment]
Yes, clicking check now populates the list. I will try the master build thanks.
I should mention that I don't use pacman-contrib but a custom script.

**Comment by moshiur-raj** [comment]
Thank you. The fix worked. I was also having problems with long lists (the list was hidden after a certain number of packages were shown). Hopefully it's fixed now.
